#!/usr/bin/env python
import os
import sys

from jinja2 import Environment, FileSystemLoader
from jinja2_highlight import HighlightExtension


HERE = os.path.abspath(os.path.dirname(__file__))
TEMPLATES = os.path.join(HERE, 'templates')
OUTPUT = os.path.join(HERE, 'output')


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.stderr.write("Usage: ./build sometpl\n")
    name = sys.argv[1]
    tpl_name = "%s.j2" % name
    output_path = os.path.join(OUTPUT, "%s.html" % name)
    # name might be like foo/bar, so then this would be OUTPUT/foo/
    output_dir = os.path.dirname(output_path)
    env = Environment(
        extensions=[HighlightExtension], loader=FileSystemLoader(TEMPLATES))
    tpl = env.get_template(tpl_name)
    html = tpl.render()
    os.makedirs(output_dir)
    with open(output_path, 'w') as fh:
        fh.write(html.encode('utf-8'))
