---
active_modules: [pygments, tags, blog, typogrify]
author: Eric A. Meyer
canonical_url: http://andmeyer.com/
output_folder: ../../pres-pages/
template_path: ../templates
modules:
  pygments:
    style: borland
  blog:
    index_url: /
